workflows:
  android-release:
    name: Android Release Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
      android_signing:
        - keystore_reference
      vars:
        PACKAGE_NAME: "com.lamafiaclamad"
      groups:
        - google_credentials
    scripts:
      - name: Set up local.properties
        script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build AAB with Flutter
        script: flutter build appbundle --release
      - name: Build APK with Flutter
        script: flutter build apk --release
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/bundle/**/*.aab
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - lidcloned@gmail.com
