name: lamafiacla
description: 'Aplicativo LaMafia: Federação - Gerenciamento de clã tático'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  intl: ^0.19.0
  flutter_svg: ^2.0.0+1
  audioplayers: ^6.4.0
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  flutter_local_notifications: ^16.2.0
  uuid: ^4.2.1
  permission_handler: ^11.0.1
  connectivity_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/audio/
    
  fonts:
    - family: Gothic
      fonts:
        - asset: assets/fonts/gothic.ttf
    - family: Digital
      fonts:
        - asset: assets/fonts/digital.ttf
